# Generated by Django 4.2.7 on 2023-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('L', 'Lifestyle'), ('H', 'Home'), ('W', 'Work'), ('R', 'Personal Relationships'), ('H', 'Health & Fitness'), ('B', 'Hobbies'), ('E', 'Environmental'), ('M', 'Miscellaneous')], default='L', max_length=1),
        ),
    ]
