# Generated by Django 4.2.7 on 2023-11-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_habit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('L', 'Lifestyle'), ('H', 'Home'), ('W', 'Work'), ('R', 'Personal Relationships'), ('F', 'Health & Fitness'), ('B', 'Hobbies'), ('E', 'Environmental'), ('M', 'Miscellaneous')], default='L', max_length=1),
        ),
    ]
